spring:
    application:
        name: retail

    datasource:
        url: jdbc:postgresql://localhost:5432/retaildb
        username: postgres
        password: 521478963
        driver-class-name: org.postgresql.Driver
        tomcat:
            test-on-borrow: true
            validation-query: SELECT 1

    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        show-sql: ${SHOW_SQL:true}
        properties:
            hibernate:
                jdbc:
                    batch_size: 10
                order_updates: true
                order_inserts: true
                format_sql: true
                generate_statistics: true
                default_schema: postgres

    flyway:
        baseline-on-migrate: true
        enabled: true
        validate-on-migrate: true
        baseline-version: 0
        schemas: postgres